import {
  AlertTriangle,
  ArrowDown,
  ArrowUp,
  Atom,
  BookOpen,
  Brain,
  Calculator,
  Car,
  Check,
  Clock,
  Cloud,
  Coins,
  Droplet,
  Factory,
  Flame,
  FlaskConical,
  Globe,
  Heart,
  Landmark,
  Leaf,
  Lightbulb,
  Map,
  Scale,
  Sigma,
  Snowflake,
  Sun,
  Target,
  Thermometer,
  TreePine,
  Users,
  Wind,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { SCENE_ICONS } from "@/lib/video/schema";

export const ICONS: Record<(typeof SCENE_ICONS)[number], LucideIcon> = {
  sun: Sun,
  cloud: Cloud,
  thermometer: Thermometer,
  globe: Globe,
  factory: Factory,
  car: Car,
  leaf: Leaf,
  tree: TreePine,
  droplet: Droplet,
  flame: Flame,
  snowflake: Snowflake,
  wind: Wind,
  zap: Zap,
  atom: Atom,
  flask: FlaskConical,
  calculator: Calculator,
  sigma: Sigma,
  scale: Scale,
  book: BookOpen,
  lightbulb: Lightbulb,
  target: Target,
  check: Check,
  alert: AlertTriangle,
  users: Users,
  landmark: Landmark,
  clock: Clock,
  "arrow-up": ArrowUp,
  "arrow-down": ArrowDown,
  heart: Heart,
  brain: Brain,
  map: Map,
  coins: Coins,
};

export function SceneIconView({ name, size = 40, color }: { name: keyof typeof ICONS | null; size?: number; color?: string }) {
  if (!name) return null;
  const Icon = ICONS[name];
  return <Icon size={size} color={color} strokeWidth={2} />;
}
