// AUTO-GENERATED by scripts/gen-types.sh – do not edit by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: { PostgrestVersion: "12" };
  public: {
    Tables: {
      adaptive_decisions: {
        Row: {
          id: string;
          user_id: string;
          project_id: string;
          session_id: string | null;
          topic_id: string | null;
          action: string;
          rule: string;
          reason: string;
          inputs: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          project_id: string;
          session_id?: string | null;
          topic_id?: string | null;
          action: string;
          rule: string;
          reason: string;
          inputs?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          project_id?: string;
          session_id?: string | null;
          topic_id?: string | null;
          action?: string;
          rule?: string;
          reason?: string;
          inputs?: Json;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "adaptive_decisions_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "study_projects";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "adaptive_decisions_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "study_sessions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "adaptive_decisions_topic_id_fkey";
            columns: ["topic_id"];
            isOneToOne: false;
            referencedRelation: "knowledge_topics";
            referencedColumns: ["id"];
          },
        ];
      };
      assessment_results: {
        Row: {
          id: string;
          user_id: string;
          project_id: string;
          attempt_id: string;
          overall: Json;
          per_question: Json;
          topic_scores: Json;
          total_score: number;
          max_score: number;
          criteria_available: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          project_id: string;
          attempt_id: string;
          overall: Json;
          per_question: Json;
          topic_scores?: Json;
          total_score: number;
          max_score: number;
          criteria_available: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          project_id?: string;
          attempt_id?: string;
          overall?: Json;
          per_question?: Json;
          topic_scores?: Json;
          total_score?: number;
          max_score?: number;
          criteria_available?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "assessment_results_attempt_id_fkey";
            columns: ["attempt_id"];
            isOneToOne: true;
            referencedRelation: "exam_attempts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "assessment_results_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "study_projects";
            referencedColumns: ["id"];
          },
        ];
      };
      clarifying_questions: {
        Row: {
          id: string;
          user_id: string;
          project_id: string;
          position: number;
          question: string;
          why: string;
          options: string[];
          allow_free_text: boolean;
          topic_keys: string[];
          answer: string | null;
          answered_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          project_id: string;
          position: number;
          question: string;
          why: string;
          options?: string[];
          allow_free_text?: boolean;
          topic_keys?: string[];
          answer?: string | null;
          answered_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          project_id?: string;
          position?: number;
          question?: string;
          why?: string;
          options?: string[];
          allow_free_text?: boolean;
          topic_keys?: string[];
          answer?: string | null;
          answered_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "clarifying_questions_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "study_projects";
            referencedColumns: ["id"];
          },
        ];
      };
      diagnostic_questions: {
        Row: {
          id: string;
          user_id: string;
          project_id: string;
          topic_id: string;
          position: number;
          question: Json;
          answered_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          project_id: string;
          topic_id: string;
          position: number;
          question: Json;
          answered_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          project_id?: string;
          topic_id?: string;
          position?: number;
          question?: Json;
          answered_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "diagnostic_questions_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "study_projects";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "diagnostic_questions_topic_id_fkey";
            columns: ["topic_id"];
            isOneToOne: false;
            referencedRelation: "knowledge_topics";
            referencedColumns: ["id"];
          },
        ];
      };
      exam_attempts: {
        Row: {
          id: string;
          user_id: string;
          project_id: string;
          mock_exam_id: string;
          status: string;
          answers: Json;
          started_at: string;
          submitted_at: string | null;
          assessed_at: string | null;
          error_message: string | null;
        };
        Insert: {
          id?: string;
          user_id?: string;
          project_id: string;
          mock_exam_id: string;
          status?: string;
          answers?: Json;
          started_at?: string;
          submitted_at?: string | null;
          assessed_at?: string | null;
          error_message?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          project_id?: string;
          mock_exam_id?: string;
          status?: string;
          answers?: Json;
          started_at?: string;
          submitted_at?: string | null;
          assessed_at?: string | null;
          error_message?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "exam_attempts_mock_exam_id_fkey";
            columns: ["mock_exam_id"];
            isOneToOne: false;
            referencedRelation: "mock_exams";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "exam_attempts_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "study_projects";
            referencedColumns: ["id"];
          },
        ];
      };
      exercise_sets: {
        Row: {
          id: string;
          user_id: string;
          project_id: string;
          topic_id: string | null;
          session_id: string | null;
          lesson_id: string | null;
          purpose: string;
          items: Json;
          status: string;
          created_at: string;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          user_id?: string;
          project_id: string;
          topic_id?: string | null;
          session_id?: string | null;
          lesson_id?: string | null;
          purpose?: string;
          items?: Json;
          status?: string;
          created_at?: string;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          project_id?: string;
          topic_id?: string | null;
          session_id?: string | null;
          lesson_id?: string | null;
          purpose?: string;
          items?: Json;
          status?: string;
          created_at?: string;
          completed_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "exercise_sets_lesson_id_fkey";
            columns: ["lesson_id"];
            isOneToOne: false;
            referencedRelation: "lesson_modules";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "exercise_sets_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "study_projects";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "exercise_sets_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "study_sessions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "exercise_sets_topic_id_fkey";
            columns: ["topic_id"];
            isOneToOne: false;
            referencedRelation: "knowledge_topics";
            referencedColumns: ["id"];
          },
        ];
      };
      knowledge_topics: {
        Row: {
          id: string;
          user_id: string;
          project_id: string;
          parent_id: string | null;
          key: string;
          title: string;
          description: string;
          importance: number;
          difficulty: number;
          evidence_type: string;
          inference_reason: string | null;
          evidence: Json;
          prerequisite_ids: string[];
          required_skills: string[];
          likely_question_types: string[];
          assessment_dimension: string;
          mastery: number | null;
          confidence: number;
          performance_pattern: string;
          last_practiced_at: string | null;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          project_id: string;
          parent_id?: string | null;
          key: string;
          title: string;
          description?: string;
          importance: number;
          difficulty: number;
          evidence_type: string;
          inference_reason?: string | null;
          evidence?: Json;
          prerequisite_ids?: string[];
          required_skills?: string[];
          likely_question_types?: string[];
          assessment_dimension: string;
          mastery?: number | null;
          confidence?: number;
          performance_pattern?: string;
          last_practiced_at?: string | null;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          project_id?: string;
          parent_id?: string | null;
          key?: string;
          title?: string;
          description?: string;
          importance?: number;
          difficulty?: number;
          evidence_type?: string;
          inference_reason?: string | null;
          evidence?: Json;
          prerequisite_ids?: string[];
          required_skills?: string[];
          likely_question_types?: string[];
          assessment_dimension?: string;
          mastery?: number | null;
          confidence?: number;
          performance_pattern?: string;
          last_practiced_at?: string | null;
          sort_order?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "knowledge_topics_parent_id_fkey";
            columns: ["parent_id"];
            isOneToOne: false;
            referencedRelation: "knowledge_topics";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "knowledge_topics_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "study_projects";
            referencedColumns: ["id"];
          },
        ];
      };
      lesson_modules: {
        Row: {
          id: string;
          user_id: string;
          project_id: string;
          topic_id: string | null;
          session_id: string | null;
          kind: string;
          title: string;
          checkpoints: Json;
          learning: Json | null;
          status: string;
          error_message: string | null;
          watch_progress: number;
          completed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          project_id: string;
          topic_id?: string | null;
          session_id?: string | null;
          kind?: string;
          title: string;
          checkpoints?: Json;
          learning?: Json | null;
          status?: string;
          error_message?: string | null;
          watch_progress?: number;
          completed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          project_id?: string;
          topic_id?: string | null;
          session_id?: string | null;
          kind?: string;
          title?: string;
          checkpoints?: Json;
          learning?: Json | null;
          status?: string;
          error_message?: string | null;
          watch_progress?: number;
          completed_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "lesson_modules_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "study_projects";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "lesson_modules_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "study_sessions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "lesson_modules_topic_id_fkey";
            columns: ["topic_id"];
            isOneToOne: false;
            referencedRelation: "knowledge_topics";
            referencedColumns: ["id"];
          },
        ];
      };
      lesson_scenes: {
        Row: {
          id: string;
          user_id: string;
          lesson_id: string;
          position: number;
          type: string;
          duration_seconds: number;
          data: Json;
        };
        Insert: {
          id?: string;
          user_id?: string;
          lesson_id: string;
          position: number;
          type: string;
          duration_seconds: number;
          data: Json;
        };
        Update: {
          id?: string;
          user_id?: string;
          lesson_id?: string;
          position?: number;
          type?: string;
          duration_seconds?: number;
          data?: Json;
        };
        Relationships: [
          {
            foreignKeyName: "lesson_scenes_lesson_id_fkey";
            columns: ["lesson_id"];
            isOneToOne: false;
            referencedRelation: "lesson_modules";
            referencedColumns: ["id"];
          },
        ];
      };
      mock_exam_questions: {
        Row: {
          id: string;
          user_id: string;
          mock_exam_id: string;
          topic_id: string | null;
          position: number;
          points: number;
          question: Json;
          source_material_ids: string[];
        };
        Insert: {
          id?: string;
          user_id?: string;
          mock_exam_id: string;
          topic_id?: string | null;
          position: number;
          points?: number;
          question: Json;
          source_material_ids?: string[];
        };
        Update: {
          id?: string;
          user_id?: string;
          mock_exam_id?: string;
          topic_id?: string | null;
          position?: number;
          points?: number;
          question?: Json;
          source_material_ids?: string[];
        };
        Relationships: [
          {
            foreignKeyName: "mock_exam_questions_mock_exam_id_fkey";
            columns: ["mock_exam_id"];
            isOneToOne: false;
            referencedRelation: "mock_exams";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "mock_exam_questions_topic_id_fkey";
            columns: ["topic_id"];
            isOneToOne: false;
            referencedRelation: "knowledge_topics";
            referencedColumns: ["id"];
          },
        ];
      };
      mock_exams: {
        Row: {
          id: string;
          user_id: string;
          project_id: string;
          kind: string;
          title: string;
          instructions: string;
          time_limit_minutes: number;
          total_points: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          project_id: string;
          kind: string;
          title: string;
          instructions?: string;
          time_limit_minutes: number;
          total_points?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          project_id?: string;
          kind?: string;
          title?: string;
          instructions?: string;
          time_limit_minutes?: number;
          total_points?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "mock_exams_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "study_projects";
            referencedColumns: ["id"];
          },
        ];
      };
      profiles: {
        Row: {
          id: string;
          display_name: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          display_name?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          display_name?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
        ];
      };
      question_attempts: {
        Row: {
          id: string;
          user_id: string;
          project_id: string;
          topic_id: string;
          source: string;
          source_ref: string | null;
          question_id: string | null;
          question_type: string;
          answer: Json | null;
          score: number;
          weight: number;
          is_correct: boolean;
          feedback: string | null;
          error_type: string | null;
          misconception: string | null;
          confidence: string | null;
          grading_method: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          project_id: string;
          topic_id: string;
          source: string;
          source_ref?: string | null;
          question_id?: string | null;
          question_type: string;
          answer?: Json | null;
          score: number;
          weight?: number;
          is_correct: boolean;
          feedback?: string | null;
          error_type?: string | null;
          misconception?: string | null;
          confidence?: string | null;
          grading_method: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          project_id?: string;
          topic_id?: string;
          source?: string;
          source_ref?: string | null;
          question_id?: string | null;
          question_type?: string;
          answer?: Json | null;
          score?: number;
          weight?: number;
          is_correct?: boolean;
          feedback?: string | null;
          error_type?: string | null;
          misconception?: string | null;
          confidence?: string | null;
          grading_method?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "question_attempts_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "study_projects";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "question_attempts_topic_id_fkey";
            columns: ["topic_id"];
            isOneToOne: false;
            referencedRelation: "knowledge_topics";
            referencedColumns: ["id"];
          },
        ];
      };
      remediation_targets: {
        Row: {
          id: string;
          user_id: string;
          project_id: string;
          assessment_id: string;
          topic_id: string | null;
          priority: number;
          title: string;
          description: string;
          baseline_mastery: number | null;
          status: string;
          resolved_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          project_id: string;
          assessment_id: string;
          topic_id?: string | null;
          priority: number;
          title: string;
          description: string;
          baseline_mastery?: number | null;
          status?: string;
          resolved_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          project_id?: string;
          assessment_id?: string;
          topic_id?: string | null;
          priority?: number;
          title?: string;
          description?: string;
          baseline_mastery?: number | null;
          status?: string;
          resolved_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "remediation_targets_assessment_id_fkey";
            columns: ["assessment_id"];
            isOneToOne: false;
            referencedRelation: "assessment_results";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "remediation_targets_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "study_projects";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "remediation_targets_topic_id_fkey";
            columns: ["topic_id"];
            isOneToOne: false;
            referencedRelation: "knowledge_topics";
            referencedColumns: ["id"];
          },
        ];
      };
      source_materials: {
        Row: {
          id: string;
          user_id: string;
          project_id: string;
          type: string;
          category: string;
          filename: string | null;
          mime_type: string | null;
          size_bytes: number | null;
          storage_path: string | null;
          extracted_text: string | null;
          normalized_text: string | null;
          extraction_method: string | null;
          page_count: number | null;
          processing_status: string;
          error_message: string | null;
          created_at: string;
          processed_at: string | null;
        };
        Insert: {
          id?: string;
          user_id?: string;
          project_id: string;
          type: string;
          category?: string;
          filename?: string | null;
          mime_type?: string | null;
          size_bytes?: number | null;
          storage_path?: string | null;
          extracted_text?: string | null;
          normalized_text?: string | null;
          extraction_method?: string | null;
          page_count?: number | null;
          processing_status?: string;
          error_message?: string | null;
          created_at?: string;
          processed_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          project_id?: string;
          type?: string;
          category?: string;
          filename?: string | null;
          mime_type?: string | null;
          size_bytes?: number | null;
          storage_path?: string | null;
          extracted_text?: string | null;
          normalized_text?: string | null;
          extraction_method?: string | null;
          page_count?: number | null;
          processing_status?: string;
          error_message?: string | null;
          created_at?: string;
          processed_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "source_materials_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "study_projects";
            referencedColumns: ["id"];
          },
        ];
      };
      study_plans: {
        Row: {
          id: string;
          user_id: string;
          project_id: string;
          version: number;
          is_active: boolean;
          rationale: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          project_id: string;
          version?: number;
          is_active?: boolean;
          rationale?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          project_id?: string;
          version?: number;
          is_active?: boolean;
          rationale?: Json;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "study_plans_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "study_projects";
            referencedColumns: ["id"];
          },
        ];
      };
      study_projects: {
        Row: {
          id: string;
          user_id: string;
          subject: string;
          title: string;
          exam_date: string;
          target_grade: string | null;
          minutes_per_session: number;
          available_days: number[];
          status: string;
          map_summary: string | null;
          map_warnings: string[];
          map_generated_at: string | null;
          has_grading_criteria: boolean;
          created_at: string;
          updated_at: string;
          clarified_at: string | null;
        };
        Insert: {
          id?: string;
          user_id?: string;
          subject: string;
          title: string;
          exam_date: string;
          target_grade?: string | null;
          minutes_per_session: number;
          available_days?: number[];
          status?: string;
          map_summary?: string | null;
          map_warnings?: string[];
          map_generated_at?: string | null;
          has_grading_criteria?: boolean;
          created_at?: string;
          updated_at?: string;
          clarified_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          subject?: string;
          title?: string;
          exam_date?: string;
          target_grade?: string | null;
          minutes_per_session?: number;
          available_days?: number[];
          status?: string;
          map_summary?: string | null;
          map_warnings?: string[];
          map_generated_at?: string | null;
          has_grading_criteria?: boolean;
          created_at?: string;
          updated_at?: string;
          clarified_at?: string | null;
        };
        Relationships: [
        ];
      };
      study_sessions: {
        Row: {
          id: string;
          user_id: string;
          project_id: string;
          plan_id: string;
          position: number;
          scheduled_date: string;
          kind: string;
          title: string;
          goal: string;
          estimated_minutes: number;
          topic_ids: string[];
          items: Json;
          status: string;
          current_step: number;
          started_at: string | null;
          completed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          project_id: string;
          plan_id: string;
          position: number;
          scheduled_date: string;
          kind: string;
          title: string;
          goal: string;
          estimated_minutes: number;
          topic_ids?: string[];
          items?: Json;
          status?: string;
          current_step?: number;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          project_id?: string;
          plan_id?: string;
          position?: number;
          scheduled_date?: string;
          kind?: string;
          title?: string;
          goal?: string;
          estimated_minutes?: number;
          topic_ids?: string[];
          items?: Json;
          status?: string;
          current_step?: number;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "study_sessions_plan_id_fkey";
            columns: ["plan_id"];
            isOneToOne: false;
            referencedRelation: "study_plans";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "study_sessions_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "study_projects";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: { [_ in never]: never };
    Functions: { [_ in never]: never };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};

type PublicTables = Database["public"]["Tables"];
export type Tables<T extends keyof PublicTables> = PublicTables[T]["Row"];
export type TablesInsert<T extends keyof PublicTables> = PublicTables[T]["Insert"];
export type TablesUpdate<T extends keyof PublicTables> = PublicTables[T]["Update"];
