/**
 * Generates src/lib/supabase/database.types.ts from a migrated database in the
 * same shape as `supabase gen types typescript`, without needing Docker.
 * Invoked by scripts/gen-types.sh.
 */
import { writeFileSync } from "node:fs";
import { Client } from "pg";

const PG_TO_TS: Record<string, string> = {
  uuid: "string",
  text: "string",
  varchar: "string",
  date: "string",
  timestamptz: "string",
  timestamp: "string",
  bool: "boolean",
  int2: "number",
  int4: "number",
  int8: "number",
  float4: "number",
  float8: "number",
  numeric: "number",
  jsonb: "Json",
  json: "Json",
};

function tsType(udt: string): string {
  if (udt.startsWith("_")) return `${tsType(udt.slice(1))}[]`;
  const t = PG_TO_TS[udt];
  if (!t) throw new Error(`Unmapped postgres type: ${udt}`);
  return t;
}

async function main() {
  const db = process.argv[2];
  const client = new Client({ database: db });
  await client.connect();

  const cols = await client.query<{
    table_name: string;
    column_name: string;
    udt_name: string;
    is_nullable: "YES" | "NO";
    column_default: string | null;
  }>(`
    select table_name, column_name, udt_name, is_nullable, column_default
    from information_schema.columns
    where table_schema = 'public'
    order by table_name, ordinal_position`);

  const fks = await client.query<{
    table_name: string;
    constraint_name: string;
    columns: string[];
    referenced_table: string;
    referenced_columns: string[];
    is_unique: boolean;
  }>(`
    select
      c.conrelid::regclass::text as table_name,
      c.conname as constraint_name,
      array(select attname from pg_attribute where attrelid = c.conrelid and attnum = any(c.conkey))::text[] as columns,
      c.confrelid::regclass::text as referenced_table,
      array(select attname from pg_attribute where attrelid = c.confrelid and attnum = any(c.confkey))::text[] as referenced_columns,
      exists (
        select 1 from pg_index i
        where i.indrelid = c.conrelid and i.indisunique and i.indpred is null and i.indkey::int2[] @> c.conkey and array_length(i.indkey::int2[], 1) = array_length(c.conkey, 1)
      ) as is_unique
    from pg_constraint c
    join pg_namespace n on n.oid = c.connamespace
    where c.contype = 'f' and n.nspname = 'public'
    order by 1, 2`);

  await client.end();

  const tables = new Map<string, typeof cols.rows>();
  for (const row of cols.rows) {
    if (!tables.has(row.table_name)) tables.set(row.table_name, []);
    tables.get(row.table_name)!.push(row);
  }

  const out: string[] = [];
  out.push("// AUTO-GENERATED by scripts/gen-types.sh – do not edit by hand.");
  out.push("");
  out.push("export type Json =");
  out.push("  | string");
  out.push("  | number");
  out.push("  | boolean");
  out.push("  | null");
  out.push("  | { [key: string]: Json | undefined }");
  out.push("  | Json[];");
  out.push("");
  out.push("export type Database = {");
  out.push('  __InternalSupabase: { PostgrestVersion: "12" };');
  out.push("  public: {");
  out.push("    Tables: {");
  for (const [table, columns] of tables) {
    out.push(`      ${table}: {`);
    out.push("        Row: {");
    for (const c of columns) {
      out.push(`          ${c.column_name}: ${tsType(c.udt_name)}${c.is_nullable === "YES" ? " | null" : ""};`);
    }
    out.push("        };");
    for (const kind of ["Insert", "Update"] as const) {
      out.push(`        ${kind}: {`);
      for (const c of columns) {
        const optional = kind === "Update" || c.is_nullable === "YES" || c.column_default !== null;
        out.push(`          ${c.column_name}${optional ? "?" : ""}: ${tsType(c.udt_name)}${c.is_nullable === "YES" ? " | null" : ""};`);
      }
      out.push("        };");
    }
    out.push("        Relationships: [");
    for (const fk of fks.rows.filter((f) => f.table_name.replace(/^public\./, "") === table)) {
      const ref = fk.referenced_table.replace(/^public\./, "");
      if (ref.includes(".")) continue; // auth.users etc. are not exposed
      out.push("          {");
      out.push(`            foreignKeyName: "${fk.constraint_name}";`);
      out.push(`            columns: [${fk.columns.map((c) => `"${c}"`).join(", ")}];`);
      out.push(`            isOneToOne: ${fk.is_unique};`);
      out.push(`            referencedRelation: "${ref}";`);
      out.push(`            referencedColumns: [${fk.referenced_columns.map((c) => `"${c}"`).join(", ")}];`);
      out.push("          },");
    }
    out.push("        ];");
    out.push("      };");
  }
  out.push("    };");
  out.push("    Views: { [_ in never]: never };");
  out.push("    Functions: { [_ in never]: never };");
  out.push("    Enums: { [_ in never]: never };");
  out.push("    CompositeTypes: { [_ in never]: never };");
  out.push("  };");
  out.push("};");
  out.push("");
  out.push('type PublicTables = Database["public"]["Tables"];');
  out.push("export type Tables<T extends keyof PublicTables> = PublicTables[T][\"Row\"];");
  out.push("export type TablesInsert<T extends keyof PublicTables> = PublicTables[T][\"Insert\"];");
  out.push("export type TablesUpdate<T extends keyof PublicTables> = PublicTables[T][\"Update\"];");
  out.push("");

  writeFileSync("src/lib/supabase/database.types.ts", out.join("\n"));
  console.log(`Wrote types for ${tables.size} tables`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
